import { CartGame, Game } from "@/interfaces";



export const games: Game[] = [
  {
    id: "far-cry-6",
    title: "Far Cry 6",
    platforms: ["PC", "PS5", "Xbox"],
    price: 59.99,
    image: "/assets/images/action/farcry.png",
    category: ["Action", "Shooter"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 960",
    available: ["Worldwide"],
    status: "available",
    description: "A guerrilla revolution erupts on the tropical island of Yara. Fight to free your people in this explosive shooter.",
    rating: 3.6,
    releaseInfo: {
      developer: "Ubisoft Toronto",
      releaseDate: "2021-10-07",
      publisher: "Ubisoft",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "god-of-war",
    title: "God of War",
    platforms: ["PC", "PS5"],
    price: 49.99,
    image: "/assets/images/action/godofwarlg.png",
    category: ["Action"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 1060",
    available: ["Worldwide"],
    status: "available",
    description: "Kratos and Atreus embark on a mythical Norse journey to uncover deep truths and face powerful gods.",
    rating: 4.8,
    releaseInfo: {
      developer: "Santa Monica Studio",
      releaseDate: "2018-04-20",
      publisher: "Sony Interactive Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "spider-man",
    title: "Spider-Man",
    platforms: ["PS5", "PC"],
    price: 59.99,
    image: "/assets/images/action/spidermanlg.png",
    category: ["Action"],
    systemRequirements: "Windows 10, 16GB RAM, RTX 2060",
    available: ["Worldwide"],
    status: "available",
    description: "Swing through New York as Spider-Man and battle iconic villains in an action-packed open world.",
    rating: 4.7,
    releaseInfo: {
      developer: "Insomniac Games",
      releaseDate: "2018-09-07",
      publisher: "Sony Interactive Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "inzoi",
    title: "Inzoi",
    platforms: ["PC"],
    price: 29.99,
    image: "/assets/images/simulation/inzoilg.png",
    category: ["Simulation", "RPG"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 1050 Ti",
    available: ["Worldwide"],
    status: "coming_soon",
    description: "A life simulation game where you shape your own virtual reality, emotions, and relationships.",
    rating: 4.1,
    releaseInfo: {
      developer: "KRAFTON",
      releaseDate: "2025-11-15", // upcoming expected date
      publisher: "KRAFTON Inc.",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "rdr2",
    title: "Red Dead Redemption 2",
    platforms: ["PC", "PS5", "Xbox"],
    price: 69.99,
    image: "/assets/images/action/Reddead2lg.png",
    category: ["Action", "Adventure", "RPG"],
    systemRequirements: "Windows 10, 12GB RAM, GTX 1060",
    available: ["Worldwide"],
    status: "available",
    description: "Step into the wild west as Arthur Morgan, surviving against the decline of the outlaw era in a vast and gritty world.",
    rating: 4.8,
    releaseInfo: {
      developer: "Rockstar Games",
      releaseDate: "2018-10-26",
      publisher: "Rockstar Games",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    platforms: ["PC", "PS5", "Xbox"],
    price: 69.99,
    image: "/assets/images/RPG/Eldenringlg.png",
    category: ["RPG", "Adventure"],
    systemRequirements: "Windows 10, 16GB RAM, GTX 1070",
    available: ["Worldwide"],
    status: "available",
    description: "A dark fantasy action RPG where players traverse a vast world guided by grace to become the Elden Lord.",
    rating: 4.3,
    releaseInfo: {
      developer: "FromSoftware",
      releaseDate: "2022-02-25",
      publisher: "Bandai Namco Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "horizon-zero-dawn",
    title: "Horizon Zero Dawn",
    platforms: ["PC", "PS4"],
    price: 49.99,
    image: "/assets/images/Adventure/Horizonlg.png",
    category: ["Adventure", "Action"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 1050 Ti",
    available: ["Worldwide"],
    status: "available",
    description: "Aloy’s journey through a post-apocalyptic world ruled by robotic creatures reveals her destiny and the truth of the old world.",
    rating: 4.7,
    releaseInfo: {
      developer: "Guerrilla Games",
      releaseDate: "2017-02-28",
      publisher: "Sony Interactive Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "xcom-2",
    title: "XCOM 2",
    platforms: ["PC", "PS4", "Xbox"],
    price: 49.99,
    image: "/assets/images/strategy/XCOM2lg.png",
    category: ["Strategy"],
    systemRequirements: "Windows 7, 4GB RAM, GTX 460",
    available: ["Worldwide"],
    status: "available",
    description: "Lead the resistance against an alien occupation in this intense turn-based strategy game.",
    rating: 4.5,
    releaseInfo: {
      developer: "Firaxis Games",
      releaseDate: "2016-02-05",
      publisher: "2K Games",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "starfield",
    title: "Starfield",
    platforms: ["PC", "Xbox"],
    price: 69.99,
    image: "/assets/images/action/starfieldlg.png",
    category: ["RPG", "Adventure"],
    systemRequirements: "Windows 10, 16GB RAM, RTX 2070",
    available: ["Worldwide"],
    status: "available",
    description: "Explore space and uncover humanity's greatest mystery in this next-gen RPG from the creators of Skyrim.",
    rating: 3.1,
    releaseInfo: {
      developer: "Bethesda Game Studios",
      releaseDate: "2023-09-06",
      publisher: "Bethesda Softworks",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "gta-v",
    title: "Grand Theft Auto V",
    platforms: ["PC", "PS4", "Xbox"],
    price: 29.99,
    image: "/assets/images/action/gtavlg.png",
    category: ["Action", "Adventure"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 660",
    available: ["Worldwide"],
    status: "available",
    description: "Experience life in the crime-filled streets of Los Santos through three iconic characters in a vast open world.",
    rating: 4.4,
    releaseInfo: {
      developer: "Rockstar North",
      releaseDate: "2013-09-17",
      publisher: "Rockstar Games",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "outlast",
    title: "Outlast",
    platforms: ["PC", "PS4"],
    price: 19.99,
    image: "/assets/images/action/outlastlg.png",
    category: ["Horror", "Shooter", "Action"],
    systemRequirements: "Windows 7, 4GB RAM, GTX 260",
    available: ["Worldwide"],
    status: "available",
    description: "A terrifying survival horror game where you must escape a haunted asylum with only your camera.",
    rating: 4.5,
    releaseInfo: {
      developer: "Red Barrels",
      releaseDate: "2013-09-04",
      publisher: "Red Barrels",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "assassins-creed-valhalla",
    title: "Assassin's Creed Valhalla",
    platforms: ["PC", "PS5", "Xbox"],
    price: 59.99,
    image: "/assets/images/RPG/Assassincreedlg.png",
    category: ["RPG", "Action"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 960",
    available: ["Worldwide"],
    status: "available",
    description: "Become Eivor, a legendary Viking raider, and lead your clan in battles across England's Dark Ages.",
    rating: 3.6,
    releaseInfo: {
      developer: "Ubisoft Montreal",
      releaseDate: "2020-11-10",
      publisher: "Ubisoft",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "detroit-become-human",
    title: "Detroit: Become Human",
    platforms: ["PC", "PS4"],
    price: 39.99,
    image: "/assets/images/Adventure/detriotlg.png",
    category: ["Adventure"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 780",
    available: ["Worldwide"],
    status: "available",
    description: "Experience a gripping narrative set in a futuristic Detroit where androids face moral dilemmas.",
    rating: 4.9,
    releaseInfo: {
      developer: "Quantic Dream",
      releaseDate: "2018-05-25",
      publisher: "Sony Interactive Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "little-nightmares",
    title: "Little Nightmares",
    platforms: ["PC", "PS4", "Switch"],
    price: 24.99,
    image: "/assets/images/Adventure/littlenightmarelg.png",
    category: ["Horror", "Indie", "Adventure"],
    systemRequirements: "Windows 10, 4GB RAM, GTX 660",
    available: ["Worldwide"],
    status: "available",
    description: "Immerse yourself in a dark whimsical tale of childhood fears inside a mysterious vessel called The Maw.",
    rating: 4.5,
    releaseInfo: {
      developer: "Tarsier Studios",
      releaseDate: "2017-04-28",
      publisher: "Bandai Namco Entertainment",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "resident-evil",
    title: "Resident Evil",
    platforms: ["PC", "PS4"],
    price: 39.99,
    image: "/assets/images/Adventure/residentevillg.png",
    category: ["Horror", "Adventure"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 960",
    available: ["Worldwide"],
    status: "available",
    description: "Survive a zombie-infested world as you uncover disturbing secrets behind bioterrorism.",
    rating: 4.6,
    releaseInfo: {
      developer: "Capcom",
      releaseDate: "7 May 2021", // First RE release; you can update to RE2/RE7 if needed
      publisher: "Capcom",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "witcher-3",
    title: "The Witcher 3: Wild Hunt",
    platforms: ["PC", "PS5", "Xbox"],
    price: 39.99,
    image: "/assets/images/RPG/witcher3lg.png",
    category: ["RPG", "Adventure"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 770",
    available: ["Worldwide"],
    status: "available",
    description: "Play as Geralt of Rivia in a vast open world filled with monsters, magic, and political intrigue.",
    rating: 4.7,
    releaseInfo: {
      developer: "CD Projekt Red",
      releaseDate: "2015-05-19",
      publisher: "CD Projekt",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "league-of-legends",
    title: "League of Legends",
    platforms: ["PC"],
    price: 0.0,
    image: "/assets/images/RPG/leagueoflegendslg.png",
    category: ["Strategy", "Multiplayer"],
    systemRequirements: "Windows 7, 4GB RAM, Intel HD Graphics 3000",
    available: ["Worldwide"],
    status: "available",
    description: "Compete in 5v5 multiplayer battles using unique champions with tactical abilities and strategies.",
    rating: 3.7,
    releaseInfo: {
      developer: "Riot Games",
      releaseDate: "2009-10-27",
      publisher: "Riot Games",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "call-of-duty",
    title: "Call of Duty",
    platforms: ["PC", "PS5", "Xbox"],
    price: 59.99,
    image: "/assets/images/shooter/callofduty2sm.png",
    category: ["Shooter", "Action"],
    systemRequirements: "Windows 10, 12GB RAM, GTX 970",
    available: ["Worldwide"],
    status: "available",
    description: "Jump into cinematic military campaigns and fast-paced multiplayer gunfights in this iconic series.",
    rating: 4.0,
    releaseInfo: {
      developer: "Infinity Ward",
      releaseDate: "2024-10-25",
      publisher: "Activision",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "stalker",
    title: "S.T.A.L.K.E.R.",
    platforms: ["PC"],
    price: 29.99,
    image: "/assets/images/shooter/S.T.A.L.K.E.R.lg.png",
    category: ["RPG", "Horror", "Shooter"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 760",
    available: ["Worldwide"],
    status: "available",
    description: "Navigate through the post-apocalyptic Chernobyl Exclusion Zone full of radiation and mutated horrors.",
    rating: 4.2,
    releaseInfo: {
      developer: "GSC Game World",
      releaseDate: "2007-03-20",
      publisher: "THQ",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "bully",
    title: "Bully",
    platforms: ["PC", "PS4"],
    price: 19.99,
    image: "/assets/images/simulation/bully.png",
    category: ["Simulation", "Adventure"],
    systemRequirements: "Windows 10, 4GB RAM, Intel HD Graphics",
    available: ["Worldwide"],
    status: "available",
    description: "Play as a mischievous student at Bullworth Academy, surviving school life with humor and rebellion.",
    rating: 4.6,
    releaseInfo: {
      developer: "Rockstar Vancouver",
      releaseDate: "2006-10-17",
      publisher: "Rockstar Games",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "sims-4",
    title: "The Sims 4",
    platforms: ["PC"],
    price: 0.0,
    image: "/assets/images/simulation/thesims4lg.png",
    category: ["Simulation"],
    systemRequirements: "Windows 10, 4GB RAM, GTX 650",
    available: ["Worldwide"],
    status: "available",
    description: "Build homes, create Sims, and control their lives in this beloved life simulation game.",
    rating: 3.9,
    releaseInfo: {
      developer: "Maxis",
      releaseDate: "2014-09-02",
      publisher: "Electronic Arts",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "peak",
    title: "Peak",
    platforms: ["Mobile", "PC"],
    price: 7.0,
    image: "/assets/images/simulation/Peaklg.png",
    category: ["Simulation", "Adventure"],
    systemRequirements: "N/A",
    available: ["Worldwide"],
    status: "available",
    description: "Train your brain daily with fun games designed to challenge memory, focus, and problem-solving.",
    rating: 4.5,
    releaseInfo: {
      developer: "Brainbow",
      releaseDate: "2014-05-01",
      publisher: "Brainbow",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "nba-2k24",
    title: "NBA 2K24",
    platforms: ["PC", "PS5", "Xbox"],
    price: 69.99,
    image: "/assets/images/Sports/nba2k24lg.png",
    category: ["Sports"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 770",
    available: ["Worldwide"],
    status: "available",
    description: "Hit the court with realistic gameplay, updated rosters, and thrilling MyCareer and franchise modes.",
    rating: 2.0,
    releaseInfo: {
      developer: "Visual Concepts",
      releaseDate: "2023-09-08",
      publisher: "2K",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "fifa-24",
    title: "FIFA 24",
    platforms: ["PC", "PS5", "Xbox"],
    price: 69.99,
    image: "/assets/images/Sports/fifalg.png",
    category: ["Sports"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 960",
    available: ["Worldwide"],
    status: "available",
    description: "Experience world-class football with hyper-realistic graphics and exciting modes like Ultimate Team.",
    rating: 4.6,
    releaseInfo: {
      developer: "EA Sports",
      releaseDate: "2023-09-29",
      publisher: "Electronic Arts",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "forza-horizon-5",
    title: "Forza Horizon 5",
    platforms: ["PC", "Xbox"],
    price: 59.99,
    image: "/assets/images/Sports/forzahorlg.png",
    category: ["sports", "Simulation"],
    systemRequirements: "Windows 10, 8GB RAM, GTX 970",
    available: ["Worldwide"],
    status: "available",
    description: "Drive across vibrant Mexico in dynamic seasons with hundreds of the world's greatest cars.",
    rating: 4.2,
    releaseInfo: {
      developer: "Playground Games",
      releaseDate: "2021-11-09",
      publisher: "Xbox Game Studios",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    platforms: ["PC", "Switch", "Mobile"],
    price: 14.99,
    image: "/assets/images/strategy/stardewlg.png",
    category: ["Indie", "Simulation", "Strategy"],
    systemRequirements: "Windows Vista, 2GB RAM, 256MB VRAM",
    available: ["Worldwide"],
    status: "available",
    description: "Escape to the countryside and cultivate your dream farm in this charming farming and life sim.",
    rating: 4.0,
    releaseInfo: {
      developer: "ConcernedApe",
      releaseDate: "2016-02-26",
      publisher: "ConcernedApe",
    },
    releaseDate: "",
    developer: "",
    publisher: ""
  },
];

export const categoriesList = [
  "All",
  "Action",
  "Adventure",
  "RPG",
  "Shooter",
  "Strategy",
  "Simulation",
  "Sports",
  "Indie",
  "Horror"
];

export const libraryGames = [
   {
      id: "elden-ring",
      title: "Elden Ring",
      rating: 4.8,
      price: 59.99,
      image: "/assets/images/RPG/Eldenringlg.png",
    },

    {
      id: "peak",
      title: "Peak",
      rating: 4.5,
      price: 7.0,
      image: "/assets/images/simulation/Peaklg.png",
    },
]

export const PCGames = [
   {
      id: "bully",
      title: "Bully",
      rating: 4.6,
      price: 0,
      image: "/assets/images/simulation/bully.png",
    },

    {
      id: "fifa-24",
      title: "FIFA 24",
      rating: 4.6,
      price: 0,
      image: "/assets/images/Sports/fifalg.png",
    },
];

export const cartGames: CartGame[] = [
  {
    id: "stalker",
    title: "S.T.A.L.K.E.R.",
    price: 29.99,
    image: "/assets/images/shooter/S.T.A.L.K.E.R.sm.png",
    quantity: 1
  },
  
  {
    id: "detroit-become-human",
    title: "Detroit: Become Human",
    price: 39.99,
    image: "/assets/images/Adventure/detroit.png",
    quantity: 1
  }
];


export const footerLinks = [
  {
    title: "Explore",
    links: [
      { title: "Browse Games", url: "/categories" },
      { title: "Wishlist", url: "/wishlist" },
      { title: "Redeem Voucher", url: "/redeem"},
    ]
  },
  {
    title: "Support",
    links: [
      { title: "Email", url: "mailto:support@nexusplay.com"},
      { title: "Help Center", url: "https://nexusplay.com/help"},
      { title: "Business Inquiries", url: "mailto:biz@nexusplay.com"}
    ]
  },
  {
    title: "Connect",
    links: [
      { title: "LinkedIn", url: "https://linkedin.com/company/nexusplay"},
      { title: "Twitter", url: "https://twitter.com/nexusplay"},
      { title: "Discord", url: "https://discord.gg/nexusplay"},
    ]
  }
];